/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.ClientController;
import Models.Client;
import java.awt.Color;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author HP OMEN
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        panel_overlay.setBackground(new Color(0,0,0,200));
        
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        tfemail = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        tfpassword = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SignIn = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panel_overlay = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(32, 32, 38));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(51, 52, 56));
        jLabel1.setText("Email");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        tfname.setBackground(new java.awt.Color(32, 32, 38));
        tfname.setForeground(new java.awt.Color(255, 255, 255));
        tfname.setBorder(null);
        tfname.setCaretColor(new java.awt.Color(255, 255, 255));
        tfname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfnameFocusGained(evt);
            }
        });
        jPanel2.add(tfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 136, 310, 20));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 310, 10));

        tfemail.setBackground(new java.awt.Color(32, 32, 38));
        tfemail.setForeground(new java.awt.Color(255, 255, 255));
        tfemail.setBorder(null);
        tfemail.setCaretColor(new java.awt.Color(255, 255, 255));
        tfemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfemailFocusGained(evt);
            }
        });
        jPanel2.add(tfemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 310, 20));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 310, 10));

        tfpassword.setBackground(new java.awt.Color(32, 32, 38));
        tfpassword.setForeground(new java.awt.Color(255, 255, 255));
        tfpassword.setBorder(null);
        tfpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfpasswordFocusGained(evt);
            }
        });
        tfpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpasswordActionPerformed(evt);
            }
        });
        jPanel2.add(tfpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 310, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 310, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(53, 111, 181));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 20, -1));

        button1.setBackground(new java.awt.Color(130, 96, 199));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("Sign Up");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel2.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 310, 40));
        button1.getAccessibleContext().setAccessibleName("btn_signup");

        jLabel4.setForeground(new java.awt.Color(51, 52, 56));
        jLabel4.setText("Password");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabel6.setForeground(new java.awt.Color(51, 52, 56));
        jLabel6.setText("If you are already a client please ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, -1));

        SignIn.setBackground(new java.awt.Color(53, 111, 181));
        SignIn.setForeground(new java.awt.Color(53, 111, 181));
        SignIn.setText("Sign in");
        SignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignInMouseClicked(evt);
            }
        });
        jPanel2.add(SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, -1, -1));

        jLabel11.setForeground(new java.awt.Color(53, 111, 181));
        jLabel11.setText("Name");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jLabel12.setForeground(new java.awt.Color(51, 52, 56));
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\fbrs.png")); // NOI18N
        jLabel12.setText("Facebook");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        jLabel14.setForeground(new java.awt.Color(51, 52, 56));
        jLabel14.setText("Find us on :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 590, 560));

        panel_overlay.setBackground(new java.awt.Color(0, 0, 0));
        panel_overlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setForeground(new java.awt.Color(51, 52, 56));
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\Webp.net-resizeimage.png")); // NOI18N
        panel_overlay.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Food So Good, You're Happy To Wait For A Table");
        panel_overlay.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        jLabel13.setForeground(new java.awt.Color(51, 52, 56));
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\isimm.png")); // NOI18N
        panel_overlay.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, -1, -1));

        getContentPane().add(panel_overlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 560));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\WallpaperRes.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfpasswordActionPerformed

    private void tfemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfemailFocusGained
        // TODO add your handling code here:
        jSeparator3.setBackground(new Color(53, 111, 181));
        jLabel1.setForeground(new Color(53, 111, 181));
        jLabel11.setForeground(new Color(51,52,56));
        jLabel4.setForeground(new Color(51,52,56));


    }//GEN-LAST:event_tfemailFocusGained

    private void tfpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfpasswordFocusGained
        // TODO add your handling code here:
        jSeparator2.setBackground(new Color(53, 111, 181));
        jLabel4.setForeground(new Color(53, 111, 181));
        jLabel11.setForeground(new Color(51,52,56));
        jLabel1.setForeground(new Color(51,52,56));

    }//GEN-LAST:event_tfpasswordFocusGained

    private void tfnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfnameFocusGained
        // TODO add your handling code here:
        jSeparator1.setBackground(new Color(53, 111, 181));
        jLabel11.setForeground(new Color(53, 111, 181));
        jLabel4.setForeground(new Color(51,52,56));
        jLabel1.setForeground(new Color(51,52,56));

    }//GEN-LAST:event_tfnameFocusGained

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         dispose ();
           System.exit (0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void SignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInMouseClicked
        // TODO add your handling code here:
        //new Login().setVisible(true);
        
         Login l1 = new Login();
                DragListener drag1 = new DragListener();
                l1.addMouseListener( drag1 );
                l1.addMouseMotionListener( drag1 );
                l1.setLocationRelativeTo(null) ;
                l1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SignInMouseClicked

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        String name = tfname.getText();
        String email = tfemail.getText();
        String password = new String(tfpassword.getPassword());
        //Checking valid args
        if(this.checkValidInfo()==true){
        Client c = new Client();
        c.setName(name);
        c.setEmail(email);
        c.setPassword(password);
        
        ClientController cc = new ClientController();
        
        int res = cc.createAccount(c);
        if( res> 0){
            JOptionPane.showMessageDialog(null, "Saved");
           // new Login().setVisible(true);
              Login l1 = new Login();
                DragListener drag1 = new DragListener();
                l1.addMouseListener( drag1 );
                l1.addMouseMotionListener( drag1 );
                l1.setLocationRelativeTo(null) ;
                l1.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Unable to save");
            JOptionPane.showMessageDialog(null, "Email is already registered or Database connection error");


        }
        }
        
        
    }//GEN-LAST:event_button1ActionPerformed

    
    public boolean checkValidInfo(){
         
        String password = new String(tfpassword.getPassword());
        //Add the @symb check later
        
        
        if(tfemail.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter a valid email");            
            return false;
        }else if(password.isEmpty()){
               JOptionPane.showMessageDialog(null, "Please enter a valid password");
               return false;
        }else if(tfname.getText().isEmpty()){
              JOptionPane.showMessageDialog(null, "Please enter a valid name");
              return false;
            
        }
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Home().setVisible(true);
                Home h1 = new Home();
                DragListener drag = new DragListener();
                h1.addMouseListener( drag );
                h1.addMouseMotionListener( drag );
                h1.setLocationRelativeTo(null) ;
                h1.setVisible(true);
                
            
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SignIn;
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel panel_overlay;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tfname;
    private javax.swing.JPasswordField tfpassword;
    // End of variables declaration//GEN-END:variables
}
