/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.AdminController;
import Controllers.StockController;
import Models.Client;
import Models.Stock;
import java.awt.Button;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP OMEN
 */
public class MainInterface extends javax.swing.JFrame {
    //Getting the logged in client info and setting them to stc
    public Client stc;
    //Stock
    
    
    public Stock sts;
    public int totalBs=0,nb_coca,nb_fanta,nb_ora,nb_boga;
    public double totalPrice=0;
  String client_email;
    public  ArrayList<String> orderarray,pricearray;
    
    //Creating default model for order table
    DefaultTableModel model;
    /**
     * Creates new form MainInterface
     */
    public MainInterface() {
        initComponents();
        pn_over.setBackground(new Color(0,0,0,200));
        showDate();
        showTime();
        totalBs=nb_boga+nb_coca+nb_fanta+nb_ora;
    }
    
    //Constructor with the sent client from login page
    public MainInterface(Client c) {
        initComponents();
        pn_over.setBackground(new Color(0,0,0,200));
        showDate();
        showTime();
        this.stc=c;
        model=(DefaultTableModel)tbl_Orders.getModel();
        totalBs=nb_boga+nb_coca+nb_fanta+nb_ora;

    }
    
    // //Constructor with the sent client from login page
    public MainInterface(Client c,Stock s) {
        initComponents();
        pn_over.setBackground(new Color(0,0,0,200));
        showDate();
        showTime();
        this.stc=c;
        this.sts=s;
        model=(DefaultTableModel)tbl_Orders.getModel();
        //Setting Food qty to 1
        bs1.setValue(1);
        bs2.setValue(1);
        bs3.setValue(1);
        bs4.setValue(1);
        fsp.setValue(1);
        //pzza
        
        ps1.setValue(1);
        ps2.setValue(1);
        ps3.setValue(1);
        ps4.setValue(1);
        
        //dds
        d1.setValue(1);
        c1.setValue(1);
        c2.setValue(1);
        c3.setValue(1);
        c4.setValue(1);
        c5.setValue(1);




        //
        rb_big.setActionCommand("Big Bag");
        rb_small.setActionCommand("Small Bag");
         client_email=c.getEmail();
         
         if(model.getRowCount()==0){
             bt_clr.setEnabled(false);
         }

    }
    
    //Displaying the date and time
    void showDate(){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        dateLab.setText(s.format(d));
        
        
    }
    
    void showTime(){
                new Timer(0,new ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent e) {
                          Date d = new Date();
                     SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                     timeLab.setText(s.format(d));
                    }
                }).start();
           
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        SignOut = new java.awt.Button();
        jl_cn = new javax.swing.JLabel();
        jLexit = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bs_state = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateLab = new javax.swing.JLabel();
        timeLab = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Orders = new javax.swing.JTable();
        bt_clr = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        fullprice = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        jLabel13 = new javax.swing.JLabel();
        pn_over = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cb_coca = new javax.swing.JCheckBox();
        cocaReg = new javax.swing.JSpinner();
        cb_fanta = new javax.swing.JCheckBox();
        cb_orangina = new javax.swing.JCheckBox();
        cb_boga = new javax.swing.JCheckBox();
        fantaReg = new javax.swing.JSpinner();
        oraReg = new javax.swing.JSpinner();
        bogaReg = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        add_boga = new java.awt.Button();
        add_coca = new java.awt.Button();
        add_fanta = new java.awt.Button();
        add_ora = new java.awt.Button();
        jLabel6 = new javax.swing.JLabel();
        prix_boga = new javax.swing.JLabel();
        prix_coca1 = new javax.swing.JLabel();
        prix_fanta = new javax.swing.JLabel();
        prix_ora = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        sts_boga = new javax.swing.JLabel();
        sts_coca = new javax.swing.JLabel();
        sts_fanta = new javax.swing.JLabel();
        sts_ora = new javax.swing.JLabel();
        boga_price = new javax.swing.JLabel();
        coca_price = new javax.swing.JLabel();
        fanta_price = new javax.swing.JLabel();
        ora_price = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        rb_small = new javax.swing.JRadioButton();
        rb_big = new javax.swing.JRadioButton();
        fsp = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel106 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel62 = new javax.swing.JLabel();
        jl_1 = new javax.swing.JLabel();
        jButton26 = new javax.swing.JButton();
        bs1 = new javax.swing.JSpinner();
        jButton27 = new javax.swing.JButton();
        bs2 = new javax.swing.JSpinner();
        jl_2 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jl_3 = new javax.swing.JLabel();
        jButton28 = new javax.swing.JButton();
        bs3 = new javax.swing.JSpinner();
        jButton29 = new javax.swing.JButton();
        bs4 = new javax.swing.JSpinner();
        jl_4 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        price_1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        price_2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        price_3 = new javax.swing.JLabel();
        price_4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        cn1 = new javax.swing.JLabel();
        c1 = new javax.swing.JSpinner();
        jLabel26 = new javax.swing.JLabel();
        c2 = new javax.swing.JSpinner();
        cn2 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        cn3 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        c3 = new javax.swing.JSpinner();
        jButton10 = new javax.swing.JButton();
        cn4 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        c4 = new javax.swing.JSpinner();
        cn5 = new javax.swing.JLabel();
        c5 = new javax.swing.JSpinner();
        jButton12 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cp1 = new javax.swing.JLabel();
        cp2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cp3 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        cp4 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        cp5 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        ps1 = new javax.swing.JSpinner();
        jLabel46 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        p2 = new javax.swing.JLabel();
        ps2 = new javax.swing.JSpinner();
        jLabel48 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        ps3 = new javax.swing.JSpinner();
        p4 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        ps4 = new javax.swing.JSpinner();
        jLabel51 = new javax.swing.JLabel();
        pp2 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        pp3 = new javax.swing.JLabel();
        pp4 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        pp1 = new javax.swing.JLabel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        dn1 = new javax.swing.JLabel();
        jButton23 = new javax.swing.JButton();
        d1 = new javax.swing.JSpinner();
        jLabel86 = new javax.swing.JLabel();
        dp1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(44, 46, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignOut.setBackground(new java.awt.Color(229, 66, 49));
        SignOut.setForeground(new java.awt.Color(226, 220, 186));
        SignOut.setLabel("Sign Out");
        SignOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignOutMouseClicked(evt);
            }
        });
        jPanel1.add(SignOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 50, -1, -1));

        jl_cn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_cn.setForeground(new java.awt.Color(204, 204, 204));
        jl_cn.setText("Name of Client Here");
        jPanel1.add(jl_cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 20, 180, -1));

        jLexit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLexit.setForeground(new java.awt.Color(226, 220, 186));
        jLexit.setText("X");
        jLexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLexitMouseClicked(evt);
            }
        });
        jPanel1.add(jLexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 10, 20, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\order.png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(157, 117, 203));
        jLabel8.setText("Stock Status");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, -1));

        bs_state.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bs_state.setForeground(new java.awt.Color(90, 255, 21));
        bs_state.setText("Boission");
        jPanel1.add(bs_state, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 80, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 113));

        jPanel2.setBackground(new java.awt.Color(45, 62, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Date :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Time :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        dateLab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dateLab.setForeground(new java.awt.Color(204, 204, 204));
        dateLab.setText("Date ");
        jPanel2.add(dateLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 140, -1));

        timeLab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        timeLab.setForeground(new java.awt.Color(204, 204, 204));
        timeLab.setText("Time ");
        jPanel2.add(timeLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 140, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 110, 380, 140));

        jPanel3.setBackground(new java.awt.Color(226, 220, 186));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_Orders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Rate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_Orders);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 420));

        bt_clr.setText("Clear All");
        bt_clr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_clrActionPerformed(evt);
            }
        });
        jPanel3.add(bt_clr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 140, 50));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Total Price");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, -1, -1));

        fullprice.setFont(new java.awt.Font("Verdana Pro Black", 1, 24)); // NOI18N
        fullprice.setForeground(new java.awt.Color(255, 102, 0));
        fullprice.setText("0");
        jPanel3.add(fullprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, -1, 60));

        button1.setBackground(new java.awt.Color(0, 255, 51));
        button1.setLabel("Confirmer");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel3.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 140, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\price.png")); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 250, 380, 670));

        pn_over.setBackground(new java.awt.Color(0, 0, 0));
        pn_over.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\boisso.png")); // NOI18N
        pn_over.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 250, 100));

        cb_coca.setForeground(new java.awt.Color(255, 255, 255));
        cb_coca.setText("Coca Cola");
        cb_coca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_cocaActionPerformed(evt);
            }
        });
        pn_over.add(cb_coca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        cocaReg.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        cocaReg.setEnabled(false);
        pn_over.add(cocaReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        cb_fanta.setForeground(new java.awt.Color(255, 255, 255));
        cb_fanta.setText("Fanta");
        cb_fanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_fantaActionPerformed(evt);
            }
        });
        pn_over.add(cb_fanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        cb_orangina.setForeground(new java.awt.Color(255, 255, 255));
        cb_orangina.setText("Orangina");
        cb_orangina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_oranginaActionPerformed(evt);
            }
        });
        pn_over.add(cb_orangina, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        cb_boga.setForeground(new java.awt.Color(255, 255, 255));
        cb_boga.setText("Boga Cidre");
        cb_boga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_bogaActionPerformed(evt);
            }
        });
        pn_over.add(cb_boga, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        fantaReg.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        fantaReg.setEnabled(false);
        pn_over.add(fantaReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        oraReg.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        oraReg.setEnabled(false);
        pn_over.add(oraReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        bogaReg.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        bogaReg.setEnabled(false);
        pn_over.add(bogaReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));
        pn_over.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 480, 10));

        add_boga.setEnabled(false);
        add_boga.setLabel("Add");
        add_boga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_bogaActionPerformed(evt);
            }
        });
        pn_over.add(add_boga, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 40, 20));

        add_coca.setEnabled(false);
        add_coca.setLabel("Add");
        add_coca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_cocaActionPerformed(evt);
            }
        });
        pn_over.add(add_coca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 40, 20));

        add_fanta.setEnabled(false);
        add_fanta.setLabel("Add");
        add_fanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_fantaActionPerformed(evt);
            }
        });
        pn_over.add(add_fanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 40, 20));

        add_ora.setEnabled(false);
        add_ora.setLabel("Add");
        add_ora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_oraActionPerformed(evt);
            }
        });
        pn_over.add(add_ora, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 40, 20));

        jLabel6.setForeground(new java.awt.Color(226, 220, 186));
        jLabel6.setText("Made by : Hamdi Guerbej ");
        pn_over.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 210, -1, -1));

        prix_boga.setForeground(new java.awt.Color(229, 66, 49));
        prix_boga.setText("Price :");
        pn_over.add(prix_boga, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        prix_coca1.setForeground(new java.awt.Color(229, 66, 49));
        prix_coca1.setText("Price : ");
        pn_over.add(prix_coca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        prix_fanta.setForeground(new java.awt.Color(229, 66, 49));
        prix_fanta.setText("Price : ");
        pn_over.add(prix_fanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        prix_ora.setForeground(new java.awt.Color(229, 66, 49));
        prix_ora.setText("Price :");
        pn_over.add(prix_ora, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\frite.png")); // NOI18N
        pn_over.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\friesgif.gif")); // NOI18N
        pn_over.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\friesgif.gif")); // NOI18N
        pn_over.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));
        pn_over.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 68, 160, -1));

        sts_boga.setForeground(new java.awt.Color(255, 255, 255));
        sts_boga.setText("0");
        pn_over.add(sts_boga, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 20, -1));

        sts_coca.setForeground(new java.awt.Color(255, 255, 255));
        sts_coca.setText("0");
        pn_over.add(sts_coca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 30, -1));

        sts_fanta.setForeground(new java.awt.Color(255, 255, 255));
        sts_fanta.setText("0");
        pn_over.add(sts_fanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 20, -1));

        sts_ora.setForeground(new java.awt.Color(255, 255, 255));
        sts_ora.setText("0");
        pn_over.add(sts_ora, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 20, -1));

        boga_price.setForeground(new java.awt.Color(229, 66, 49));
        boga_price.setText("from db");
        pn_over.add(boga_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        coca_price.setForeground(new java.awt.Color(229, 66, 49));
        coca_price.setText("from db");
        pn_over.add(coca_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        fanta_price.setForeground(new java.awt.Color(229, 66, 49));
        fanta_price.setText("from db");
        pn_over.add(fanta_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        ora_price.setForeground(new java.awt.Color(229, 66, 49));
        ora_price.setText("from db");
        pn_over.add(ora_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        jLabel105.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\Food\\fr.png")); // NOI18N
        pn_over.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 90, -1));

        jLabel104.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel104.setForeground(new java.awt.Color(51, 255, 0));
        jLabel104.setText("Order Fries");
        pn_over.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, -1, -1));

        btGroup.add(rb_small);
        rb_small.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rb_small.setForeground(new java.awt.Color(255, 255, 0));
        rb_small.setText("Small Bag");
        pn_over.add(rb_small, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 90, -1));

        btGroup.add(rb_big);
        rb_big.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rb_big.setForeground(new java.awt.Color(255, 255, 0));
        rb_big.setText("Big Bag");
        pn_over.add(rb_big, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, -1, -1));

        fsp.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        pn_over.add(fsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 50, -1));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pn_over.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 60, -1));

        jLabel106.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel106.setForeground(new java.awt.Color(153, 255, 0));
        jLabel106.setText("X");
        pn_over.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, -1, -1));

        getContentPane().add(pn_over, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 1030, 230));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 243, 1035, 10));

        jLabel62.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\Food\\imageedit_1_2211057279.png")); // NOI18N
        jPanel5.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jl_1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jl_1.setText("Big Crunch®");
        jPanel5.add(jl_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 130, -1));

        jButton26.setText("Add");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 30));

        bs1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jPanel5.add(bs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 43, 30));

        jButton27.setText("Add");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, 30));

        bs2.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jPanel5.add(bs2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 43, 30));

        jl_2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jl_2.setText("ZINGER®");
        jPanel5.add(jl_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 130, -1));

        jLabel65.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\Food\\5saye.png")); // NOI18N
        jPanel5.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 160, -1));

        jLabel66.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\Food\\Webp.net-resizeimage (1).png")); // NOI18N
        jPanel5.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        jl_3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jl_3.setText("SPICY COLONEL’S ORIGINAL ");
        jPanel5.add(jl_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 190, -1));

        jButton28.setText("Add");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, 30));

        bs3.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jPanel5.add(bs3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 43, 30));

        jButton29.setText("Add");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, -1, 30));

        bs4.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jPanel5.add(bs4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 43, 30));

        jl_4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jl_4.setText("COLONEL’S ORIGINAL ");
        jPanel5.add(jl_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 160, -1));

        jLabel69.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\Food\\2.png")); // NOI18N
        jPanel5.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 255));
        jLabel12.setText("Price:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        price_1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        price_1.setForeground(new java.awt.Color(204, 0, 0));
        price_1.setText("From DB");
        jPanel5.add(price_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 255));
        jLabel14.setText("Price:");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        price_2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        price_2.setForeground(new java.awt.Color(204, 0, 0));
        price_2.setText("From DB");
        jPanel5.add(price_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 255));
        jLabel16.setText("Price:");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        price_3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        price_3.setForeground(new java.awt.Color(204, 0, 0));
        price_3.setText("From DB");
        jPanel5.add(price_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        price_4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        price_4.setForeground(new java.awt.Color(204, 0, 0));
        price_4.setText("From DB");
        jPanel5.add(price_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 255));
        jLabel19.setText("Price:");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, -1, -1));

        jTabbedPane1.addTab("Burgers", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\Chk\\Webp.net-resizeimage.jpg")); // NOI18N
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jButton7.setText("Add");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 30));

        cn1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cn1.setText("PLATTER MEAL");
        jPanel6.add(cn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 130, -1));

        c1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jPanel6.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 43, 30));

        jLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\Chk\\c2.jpg")); // NOI18N
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        c2.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jPanel6.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 43, 30));

        cn2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cn2.setText("BUDGET MEALL");
        jPanel6.add(cn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 130, -1));

        jButton8.setText("Add");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, 30));

        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\Chk\\c3.jpg")); // NOI18N
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        cn3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cn3.setText("BASIC MEAL");
        jPanel6.add(cn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 130, -1));

        jButton9.setText("Add");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, 30));

        c3.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jPanel6.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 43, 30));

        jButton10.setText("Add");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, -1, 30));

        cn4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cn4.setText("CHICKEN BARBECUE MEAL");
        jPanel6.add(cn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 180, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\Chk\\c4.jpg")); // NOI18N
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        c4.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jPanel6.add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 43, 30));

        cn5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cn5.setText("CHICKEN DINNER MEAL ");
        jPanel6.add(cn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, 160, -1));

        c5.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jPanel6.add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 170, 43, 30));

        jButton12.setText("Add");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, -1, 30));

        jLabel35.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\Chk\\c5.jpg")); // NOI18N
        jPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 255));
        jLabel20.setText("Price:");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        cp1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cp1.setForeground(new java.awt.Color(204, 0, 0));
        cp1.setText("From DB");
        jPanel6.add(cp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        cp2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cp2.setForeground(new java.awt.Color(204, 0, 0));
        cp2.setText("From DB");
        jPanel6.add(cp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 51, 255));
        jLabel23.setText("Price:");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        cp3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cp3.setForeground(new java.awt.Color(204, 0, 0));
        cp3.setText("From DB");
        jPanel6.add(cp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(0, 51, 255));
        jLabel71.setText("Price:");
        jPanel6.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        cp4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cp4.setForeground(new java.awt.Color(204, 0, 0));
        cp4.setText("From DB");
        jPanel6.add(cp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, -1, -1));

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(0, 51, 255));
        jLabel73.setText("Price:");
        jPanel6.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, -1));

        cp5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cp5.setForeground(new java.awt.Color(204, 0, 0));
        cp5.setText("From DB");
        jPanel6.add(cp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 150, -1, -1));

        jLabel75.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(0, 51, 255));
        jLabel75.setText("Price:");
        jPanel6.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 150, -1, -1));

        jTabbedPane1.addTab("Chicken", jPanel6);

        jTabbedPane2.addTab("Fast Mix", jTabbedPane1);

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\Pizza\\Webp.net-resizeimage (2).png")); // NOI18N
        jPanel10.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        p1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        p1.setText("CHEESY CHICKEN");
        jPanel10.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 130, -1));

        jButton17.setText("Add");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 30));

        ps1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jPanel10.add(ps1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 43, 30));

        jLabel46.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\Pizza\\p2.png")); // NOI18N
        jPanel10.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jButton18.setText("Add");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, 30));

        p2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        p2.setText("BUTTER CHICKEN");
        jPanel10.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 130, -1));

        ps2.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jPanel10.add(ps2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 43, 30));

        jLabel48.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\Pizza\\p3.png")); // NOI18N
        jPanel10.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        p3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        p3.setText("LOADED SUPREME ");
        jPanel10.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 130, -1));

        jButton19.setText("Add");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, 30));

        ps3.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jPanel10.add(ps3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 43, 30));

        p4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        p4.setText("MEGA MEATLOVERS");
        jPanel10.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 130, -1));

        jButton20.setText("Add");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, -1, 30));

        ps4.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jPanel10.add(ps4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 43, 30));

        jLabel51.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\Pizza\\p4.png")); // NOI18N
        jPanel10.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        pp2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        pp2.setForeground(new java.awt.Color(204, 0, 0));
        pp2.setText("From DB");
        jPanel10.add(pp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        jLabel93.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(0, 51, 255));
        jLabel93.setText("Price:");
        jPanel10.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        jLabel94.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(0, 51, 255));
        jLabel94.setText("Price:");
        jPanel10.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        pp3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        pp3.setForeground(new java.awt.Color(204, 0, 0));
        pp3.setText("From DB");
        jPanel10.add(pp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        pp4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        pp4.setForeground(new java.awt.Color(204, 0, 0));
        pp4.setText("From DB");
        jPanel10.add(pp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, -1, -1));

        jLabel97.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(0, 51, 255));
        jLabel97.setText("Price:");
        jPanel10.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, -1));

        jLabel102.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(0, 51, 255));
        jLabel102.setText("Price:");
        jPanel10.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        pp1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        pp1.setForeground(new java.awt.Color(204, 0, 0));
        pp1.setText("From DB");
        jPanel10.add(pp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jTabbedPane3.addTab("Our Pizza", jPanel10);

        jTabbedPane2.addTab("Pizza", jTabbedPane3);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel56.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\Chk\\ddd.jpg")); // NOI18N
        jPanel8.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        dn1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        dn1.setText("HALO-HALO");
        jPanel8.add(dn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 130, -1));

        jButton23.setText("Add");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 30));

        d1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jPanel8.add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 43, 30));

        jLabel86.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(0, 51, 255));
        jLabel86.setText("Price:");
        jPanel8.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        dp1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        dp1.setForeground(new java.awt.Color(204, 0, 0));
        dp1.setText("From DB");
        jPanel8.add(dp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jTabbedPane4.addTab("Dessert", jPanel8);

        jTabbedPane2.addTab("Desserts", jTabbedPane4);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP OMEN\\Desktop\\Projectsrc\\ffff.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 1030, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLexitMouseClicked
        // TODO add your handling code here:
                   JOptionPane.showMessageDialog(null, "GoodBye "+this.stc.getName());

        dispose ();
           System.exit (0);
    }//GEN-LAST:event_jLexitMouseClicked

    private void SignOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignOutMouseClicked
        // TODO add your handling code here:
                   JOptionPane.showMessageDialog(null, "GoodBye "+this.stc.getName());

                  Login l1 = new Login();
                DragListener drag1 = new DragListener();
                l1.addMouseListener( drag1 );
                l1.addMouseMotionListener( drag1 );
                l1.setLocationRelativeTo(null) ;
                l1.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_SignOutMouseClicked

    private void cb_bogaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_bogaActionPerformed
        // TODO add your handling code here:
                        this.awakeOption(cb_boga, bogaReg, add_boga);

    }//GEN-LAST:event_cb_bogaActionPerformed

    private void add_bogaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_bogaActionPerformed
        // TODO add your handling code here:
            
            
                 if(nb_boga>0){
       double price= calculateDrinkPrice(bogaReg,Integer.parseInt(boga_price.getText()));
            model.insertRow(model.getRowCount(), new Object[]{cb_boga.getText(),bogaReg.getValue(),price});
                nb_boga-=(Integer)bogaReg.getValue();
                totalBs-=(Integer)bogaReg.getValue();
             this.CalculateTotalPrice();
               bt_clr.setEnabled(true);

}
        //todelete
        this.sts_boga.setText(""+(nb_boga));
        if(nb_boga<=0){
           // bs_state.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "No more Boga");
        }
                this.UpdateInterfaceStock();
                                    this.setTotalPrice();

    }//GEN-LAST:event_add_bogaActionPerformed

    private void cb_cocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_cocaActionPerformed
      
        this.awakeOption(cb_coca, cocaReg, add_coca);
    }//GEN-LAST:event_cb_cocaActionPerformed

    private void cb_fantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_fantaActionPerformed
        // TODO add your handling code here:
                this.awakeOption(cb_fanta, fantaReg, add_fanta);

    }//GEN-LAST:event_cb_fantaActionPerformed

    private void cb_oranginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_oranginaActionPerformed
        // TODO add your handling code here:
                this.awakeOption(cb_orangina, oraReg, add_ora);

    }//GEN-LAST:event_cb_oranginaActionPerformed

    private void add_cocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_cocaActionPerformed
        // TODO add your handling code here:
        if(nb_coca>0 && (Integer) cocaReg.getValue()<=nb_coca){
            double price = calculateDrinkPrice(cocaReg, Integer.parseInt(coca_price.getText()));
            model.insertRow(model.getRowCount(), new Object[]{cb_coca.getText(), cocaReg.getValue(), price});
            nb_coca -= (Integer) cocaReg.getValue();
            totalBs -= (Integer) cocaReg.getValue();
            System.out.println("hi");
             this.CalculateTotalPrice();
             this.setTotalPrice();
             bt_clr.setEnabled(true);
}
        //todelete
        this.sts_coca.setText(""+(nb_coca));
        if(nb_coca<=0){
           // bs_state.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "No more coca");
        }
        this.UpdateInterfaceStock();
                        

    }//GEN-LAST:event_add_cocaActionPerformed

    private void add_fantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_fantaActionPerformed
        // TODO add your handling code here:
        
        
            if(nb_fanta>0){
                double price = calculateDrinkPrice(fantaReg, Integer.parseInt(fanta_price.getText()));
                model.insertRow(model.getRowCount(), new Object[]{cb_fanta.getText(), fantaReg.getValue(), price});
                nb_fanta -= (Integer) fantaReg.getValue();
                totalBs -= (Integer) fantaReg.getValue();
             this.CalculateTotalPrice();
  bt_clr.setEnabled(true);
}
        //todelete
        this.sts_fanta.setText(""+(nb_fanta));
        if(nb_fanta<=0){
           // bs_state.setForeground(Color.red);
            bs_state.setToolTipText("test");
            JOptionPane.showMessageDialog(null, "No more fanta");
        }
                this.UpdateInterfaceStock();
                this.setTotalPrice();

        
    }//GEN-LAST:event_add_fantaActionPerformed

    private void add_oraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_oraActionPerformed
        // TODO add your handling code here:
        
        
         if(nb_ora>0){
             double price = calculateDrinkPrice(oraReg, Integer.parseInt(ora_price.getText()));
             model.insertRow(model.getRowCount(), new Object[]{cb_orangina.getText(), oraReg.getValue(), price});
             nb_ora -= (Integer) oraReg.getValue();
             totalBs -= (Integer) oraReg.getValue();
             this.CalculateTotalPrice();
               bt_clr.setEnabled(true);
}
        //todelete
        this.sts_ora.setText(""+(nb_ora));
        if(nb_ora<=0){
          // bs_state.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "No more Orangina");
        }
                this.UpdateInterfaceStock();
                this.setTotalPrice();

    }//GEN-LAST:event_add_oraActionPerformed

    private void bt_clrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_clrActionPerformed
        // TODO add your handling code here:
                          
                            
        Object[] options = {"Yes, please", "No!"};
        int n = JOptionPane.showOptionDialog(null,
                "This will delete all the ready orders, Continue?",
                "Warning!!",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);
                    if (n == JOptionPane.YES_OPTION) {
                         this.ResetStockOnDelete();
                            this.UpdateStock();
                                model.setRowCount(0);
                    } else if (n == JOptionPane.NO_OPTION) {
                            //Not needed now

                    } else {

                    }
                                        this.UpdateInterfaceStock();
                                                fullprice.setText(""+0.0);
  bt_clr.setEnabled(false);

        
    }//GEN-LAST:event_bt_clrActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int qty = (Integer)fsp.getValue();
        double bigp=1500;
        double smallp=1000;
        double price=0;
        if(btGroup.getSelection().getActionCommand()=="Big Bag"){
           
            price = bigp*qty;
            System.out.println(price);
             model.insertRow(model.getRowCount(), new Object[]{btGroup.getSelection().getActionCommand(), qty, price});
                 this.CalculateTotalPrice();
                     this.setTotalPrice();
    }else if(btGroup.getSelection().getActionCommand()=="Small Bag"){
        price = smallp*qty;
            System.out.println(price);
             model.insertRow(model.getRowCount(), new Object[]{btGroup.getSelection().getActionCommand(), qty, price});
                 this.CalculateTotalPrice();
        this.setTotalPrice();
    }
  bt_clr.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        AdminController ac = new AdminController();
        
        ac.AddOrder(client_email, fullprice.getText(),timeLab,dateLab);
        StockController sc = new StockController();
     int res =  sc.ChangeStock(cb_coca, Integer.parseInt(sts_coca.getText()));
       sc.ChangeStock(cb_fanta, Integer.parseInt(sts_fanta.getText()));
       sc.ChangeStock(cb_orangina, Integer.parseInt(sts_ora.getText()));
       sc.ChangeStock(cb_boga, Integer.parseInt(sts_boga.getText()));
       if(res>0)
           JOptionPane.showMessageDialog(null, "Order Sent To Admin , Please wait until we prepare it ! Thank you");
        model.setRowCount(0);
        fullprice.setText("0");
        System.out.println(timeLab.getText());
        
    }//GEN-LAST:event_button1ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
        double price = calculateFoodPrice(bs4, Integer.parseInt(price_4.getText()));

        model.insertRow(model.getRowCount(), new Object[]{jl_4.getText(), bs4.getValue(), price});
        this.CalculateTotalPrice();
        this.setTotalPrice();
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
        double price = calculateFoodPrice(bs3, Integer.parseInt(price_3.getText()));

        model.insertRow(model.getRowCount(), new Object[]{jl_3.getText(), bs3.getValue(), price});
        this.CalculateTotalPrice();
        this.setTotalPrice();
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
        double price = calculateFoodPrice(bs2, Integer.parseInt(price_2.getText()));

        model.insertRow(model.getRowCount(), new Object[]{jl_2.getText(), bs2.getValue(), price});
        this.CalculateTotalPrice();
        this.setTotalPrice();
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:

        double price = calculateFoodPrice(bs1, Integer.parseInt(price_1.getText()));

        model.insertRow(model.getRowCount(), new Object[]{jl_1.getText(), bs1.getValue(), price});
        this.CalculateTotalPrice();
        this.setTotalPrice();
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         double price = calculateFoodPrice(c1, Integer.parseInt(cp1.getText()));

        model.insertRow(model.getRowCount(), new Object[]{cn1.getText(), c1.getValue(), price});
        this.CalculateTotalPrice();
        this.setTotalPrice();
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        double price = calculateFoodPrice(d1, Integer.parseInt(dp1.getText()));

        model.insertRow(model.getRowCount(), new Object[]{dn1.getText(), d1.getValue(), price});
        this.CalculateTotalPrice();
        this.setTotalPrice();
        
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
           double price = calculateFoodPrice(c2, Integer.parseInt(cp2.getText()));

        model.insertRow(model.getRowCount(), new Object[]{cn2.getText(), c2.getValue(), price});
        this.CalculateTotalPrice();
        this.setTotalPrice();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
           double price = calculateFoodPrice(c3, Integer.parseInt(cp3.getText()));

        model.insertRow(model.getRowCount(), new Object[]{cn3.getText(), c3.getValue(), price});
        this.CalculateTotalPrice();
        this.setTotalPrice();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
           double price = calculateFoodPrice(c4, Integer.parseInt(cp4.getText()));

        model.insertRow(model.getRowCount(), new Object[]{cn4.getText(), c4.getValue(), price});
        this.CalculateTotalPrice();
        this.setTotalPrice();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
           double price = calculateFoodPrice(c5, Integer.parseInt(cp5.getText()));

        model.insertRow(model.getRowCount(), new Object[]{cn5.getText(), c5.getValue(), price});
        this.CalculateTotalPrice();
        this.setTotalPrice();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        
          double price = calculateFoodPrice(ps1, Integer.parseInt(pp1.getText()));

        model.insertRow(model.getRowCount(), new Object[]{p1.getText(), ps1.getValue(), price});
        this.CalculateTotalPrice();
        this.setTotalPrice();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
          double price = calculateFoodPrice(ps2, Integer.parseInt(pp2.getText()));

        model.insertRow(model.getRowCount(), new Object[]{p2.getText(), ps2.getValue(), price});
        this.CalculateTotalPrice();
        this.setTotalPrice();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
          double price = calculateFoodPrice(ps3, Integer.parseInt(pp3.getText()));

        model.insertRow(model.getRowCount(), new Object[]{p3.getText(), ps3.getValue(), price});
        this.CalculateTotalPrice();
        this.setTotalPrice();
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
          double price = calculateFoodPrice(ps4, Integer.parseInt(pp4.getText()));

        model.insertRow(model.getRowCount(), new Object[]{p4.getText(), ps4.getValue(), price});
        this.CalculateTotalPrice();
        this.setTotalPrice();
    }//GEN-LAST:event_jButton20ActionPerformed

//Setting the name of the client in the main interface
    void setLc(String name){
        jl_cn.setText("Welcome "+name);
    }
    
    //To delete later/working fine
             void getClient(Client c){
           
            stc.setName(c.getName());
            stc.setEmail(c.getEmail());
            stc.setPassword(c.getPassword());
                 System.out.println(""+stc.getName());
                   }
         //testing client
         
             
             //To delete later (new 21/02/2018) adding the stock /working fine
                    void getStock(Stock s){
                        StockController sc = new StockController();
                        sts.setBoissonName(cb_coca.getText());
                        nb_coca=sc.getBoissonStock(sts);
                        //getting fanta number
                          sts.setBoissonName(cb_fanta.getText());
                        nb_fanta=sc.getBoissonStock(sts);
                        //getting orangina number
                          sts.setBoissonName(cb_orangina.getText());
                        nb_ora=sc.getBoissonStock(sts);
                        //getting boga number
                            sts.setBoissonName(cb_boga.getText());
                        nb_boga=sc.getBoissonStock(sts);
                                totalBs=nb_boga+nb_coca+nb_fanta+nb_ora;
                System.out.println("Stock total="+totalBs);

                
                        //Setting the price on the food in the jlabels
                        this.setFoodPrice(sc,jl_1,price_1);
                        this.setFoodPrice(sc,jl_2,price_2);
                        this.setFoodPrice(sc,jl_3,price_3);
                        this.setFoodPrice(sc,jl_4,price_4);
                        
                        //Pizza
                         this.setPizzaPrice(sc,p1,pp1);
                         this.setPizzaPrice(sc,p2,pp2);
                         this.setPizzaPrice(sc,p3,pp3);
                         this.setPizzaPrice(sc,p4,pp4);

                //Chicken
                         this.setChickenPrice(sc,cn1,cp1);
                         this.setChickenPrice(sc,cn2,cp2);
                         this.setChickenPrice(sc,cn3,cp3);
                         this.setChickenPrice(sc,cn4,cp4);
                         this.setChickenPrice(sc,cn5,cp5);
               //Dessrt
                         this.setDessertPrice(sc,dn1,dp1);
                
                
                         //
                        
                        //System.out.println(""+sc.getBoissonStock(sts));  
                        /*this.sts_coca.setText(""+sc.getBoissonStock(sts));
                        sts.setBoissonName(cb_fanta.getText());
                        this.sts_fanta.setText(""+sc.getBoissonStock(sts));
                        sts.setBoissonName(cb_orangina.getText());
                        this.sts_ora.setText(""+sc.getBoissonStock(sts));*/
                        
                        this.setBoissonStock(sts, sc, cb_coca, sts_coca);
                        this.setBoissonStock(sts, sc, cb_fanta, sts_fanta);
                        this.setBoissonStock(sts, sc, cb_orangina, sts_ora);
                        this.setBoissonStock(sts, sc, cb_boga, sts_boga);
                        
                        //setting the price to tfds
                          
                        this.setBoissonPrice(sts, sc, cb_coca, coca_price);
                        this.setBoissonPrice(sts, sc, cb_fanta, fanta_price);
                        this.setBoissonPrice(sts, sc, cb_orangina, ora_price);
                        this.setBoissonPrice(sts, sc, cb_boga, boga_price);
  
                    }
             //To here
                    
                    //To delete later
                                void setBoissonStock(Stock sts,StockController sc,JCheckBox cb,JLabel jl){
                                    sts.setBoissonName(cb.getText());
                                    jl.setText(""+sc.getBoissonStock(sts));
                                    
                                    
                                    
                                }
                    //To here
                                
                                
                                //
                                 void setFoodPrice(StockController sc,JLabel jl,JLabel mjl){
                                     
                                     mjl.setText(""+sc.getFoodPrice(jl));
                                     
                                 }
                                //
                                 
                                 
                                 //Setting Pizza Price
                                  void setPizzaPrice(StockController sc,JLabel jl,JLabel mjl){
                                     
                                     mjl.setText(""+sc.getPizzaPrice(jl));
                                     
                                 }
                                 //
                                  
                                  //Chiken
                                   void setChickenPrice(StockController sc,JLabel jl,JLabel mjl){
                                     
                                     mjl.setText(""+sc.getChickenPrice(jl));
                                     
                                 }
                                  
                                  //Dessert
                                   
                                    void setDessertPrice(StockController sc,JLabel jl,JLabel mjl){
                                     
                                     mjl.setText(""+sc.getDessertPrice(jl));
                                     
                                 }
                                   
                                   //
                                
                 //Getting the price from db               
            void setBoissonPrice(Stock sts,StockController sc,JCheckBox cb,JLabel jl){
                                    sts.setBoissonName(cb.getText());
                                    jl.setText(""+sc.getBoissonPrice(sts));
                                    
                                    
                                    
                                }    
            //ends here 
            
    //Awaking the options 
    void awakeOption(JCheckBox cb,JSpinner s,Button b){
        if(cb.isSelected()){
            s.setEnabled(true);
            b.setEnabled(true);
            s.setValue(1);
         }else{
               s.setEnabled(false);
            b.setEnabled(false);
             s.setValue(0);
             
         }
      
    }
    
    
    double calculateDrinkPrice(JSpinner js,double price){
        return((Integer)js.getValue()*price);
    }
    
    
    
    double calculateFoodPrice(JSpinner js,double price){
        return((Integer)js.getValue()*price);
    }
    
    
    void UpdateInterfaceStock(){
        System.out.println(totalBs);
        if(totalBs<=0){
        bs_state.setForeground(Color.red);

        }else{
            bs_state.setForeground(Color.green);
        }
    }
    
    void UpdateStock(){
                totalBs=nb_boga+nb_coca+nb_fanta+nb_ora;

                this.sts_coca.setText(""+(nb_coca));
                this.sts_fanta.setText(""+(nb_fanta));
                this.sts_ora.setText(""+(nb_ora));
                this.sts_boga.setText(""+(nb_boga));

                         System.out.println("Stock total after="+totalBs);


        
    }
    
    void ResetStockOnDelete(){
        int counter=0;

        orderarray = new ArrayList<String>();

         for(int count = 0; count < model.getRowCount(); count++){
         orderarray.add(model.getValueAt(count, 0).toString());
         orderarray.add(model.getValueAt(count, 1).toString());

    }
         
        
             System.out.println( Arrays.toString(orderarray.toArray()));
     
       while(!orderarray.isEmpty()){
           if(orderarray.get(counter)=="Coca Cola"){
                nb_coca+=Integer.parseInt(orderarray.get(counter+1));
                orderarray.remove(counter+1);
                orderarray.remove(counter);
                

          }else if(orderarray.get(counter)=="Fanta"){
                nb_fanta+=Integer.parseInt(orderarray.get(counter+1));
                orderarray.remove(counter+1);
                orderarray.remove(counter);
       }else if(orderarray.get(counter)=="Orangina"){
                nb_ora+=Integer.parseInt(orderarray.get(counter+1));
                orderarray.remove(counter+1);
                orderarray.remove(counter);
       }else if(orderarray.get(counter)=="Boga Cidre"){
                nb_boga+=Integer.parseInt(orderarray.get(counter+1));
                orderarray.remove(counter+1);
                orderarray.remove(counter);
       }//to prevent crash if someone tries to edit the name lazemni nsala7aa b methode ma5ir ama heka t3adi rou7a tawa
       else {
            orderarray.remove(counter+1);
                orderarray.remove(counter);
       }
            
       
       }
       
       
        System.out.println("nb coca = "+nb_coca);
           System.out.println("nb fanta ="+nb_fanta);

    }
    
    
   /* void PrepareList(){
          int counter=0;

        orderarray = new ArrayList<String>();

         for(int count = 0; count < model.getRowCount(); count++){
         orderarray.add(model.getValueAt(count, 0).toString());
         orderarray.add(model.getValueAt(count, 1).toString());

    }
                      System.out.println( Arrays.toString(orderarray.toArray()));

        
    }*/
    
    void CalculateTotalPrice(){
     
         pricearray = new ArrayList<String>();

        for(int count = 0; count < model.getRowCount(); count++){
         pricearray.add(model.getValueAt(count, 2).toString());
        
        }
   
         
                      System.out.println( Arrays.toString(pricearray.toArray()));
        
    }
    
    
    void setTotalPrice(){
           int counter=0;
           totalPrice=0;
                    for(int count = 0; count < pricearray.size(); count++){

                                     totalPrice+=Double.parseDouble(pricearray.get(count));
                    }
               
        System.out.println("total price ="+totalPrice);
        fullprice.setText(""+totalPrice/1000+" DT");
    }
    
    
    void addBurgers(JSpinner js,JLabel jl){
        
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainInterface().setVisible(true);
                MainInterface m = new MainInterface();
              DragListener drag1 = new DragListener();
            m.addMouseListener(drag1);
            m.addMouseMotionListener(drag1);
            m.setLocationRelativeTo(null);
            m.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button SignOut;
    private java.awt.Button add_boga;
    private java.awt.Button add_coca;
    private java.awt.Button add_fanta;
    private java.awt.Button add_ora;
    private javax.swing.JSpinner bogaReg;
    private javax.swing.JLabel boga_price;
    private javax.swing.JSpinner bs1;
    private javax.swing.JSpinner bs2;
    private javax.swing.JSpinner bs3;
    private javax.swing.JSpinner bs4;
    private javax.swing.JLabel bs_state;
    private javax.swing.ButtonGroup btGroup;
    private javax.swing.JButton bt_clr;
    private java.awt.Button button1;
    private javax.swing.JSpinner c1;
    private javax.swing.JSpinner c2;
    private javax.swing.JSpinner c3;
    private javax.swing.JSpinner c4;
    private javax.swing.JSpinner c5;
    private javax.swing.JCheckBox cb_boga;
    private javax.swing.JCheckBox cb_coca;
    private javax.swing.JCheckBox cb_fanta;
    private javax.swing.JCheckBox cb_orangina;
    private javax.swing.JLabel cn1;
    private javax.swing.JLabel cn2;
    private javax.swing.JLabel cn3;
    private javax.swing.JLabel cn4;
    private javax.swing.JLabel cn5;
    private javax.swing.JSpinner cocaReg;
    private javax.swing.JLabel coca_price;
    private javax.swing.JLabel cp1;
    private javax.swing.JLabel cp2;
    private javax.swing.JLabel cp3;
    private javax.swing.JLabel cp4;
    private javax.swing.JLabel cp5;
    private javax.swing.JSpinner d1;
    private javax.swing.JLabel dateLab;
    private javax.swing.JLabel dn1;
    private javax.swing.JLabel dp1;
    private javax.swing.JSpinner fantaReg;
    private javax.swing.JLabel fanta_price;
    private javax.swing.JSpinner fsp;
    private javax.swing.JLabel fullprice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLexit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JLabel jl_1;
    private javax.swing.JLabel jl_2;
    private javax.swing.JLabel jl_3;
    private javax.swing.JLabel jl_4;
    private javax.swing.JLabel jl_cn;
    private javax.swing.JSpinner oraReg;
    private javax.swing.JLabel ora_price;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    private javax.swing.JPanel pn_over;
    private javax.swing.JLabel pp1;
    private javax.swing.JLabel pp2;
    private javax.swing.JLabel pp3;
    private javax.swing.JLabel pp4;
    private javax.swing.JLabel price_1;
    private javax.swing.JLabel price_2;
    private javax.swing.JLabel price_3;
    private javax.swing.JLabel price_4;
    private javax.swing.JLabel prix_boga;
    private javax.swing.JLabel prix_coca1;
    private javax.swing.JLabel prix_fanta;
    private javax.swing.JLabel prix_ora;
    private javax.swing.JSpinner ps1;
    private javax.swing.JSpinner ps2;
    private javax.swing.JSpinner ps3;
    private javax.swing.JSpinner ps4;
    private javax.swing.JRadioButton rb_big;
    private javax.swing.JRadioButton rb_small;
    private javax.swing.JLabel sts_boga;
    private javax.swing.JLabel sts_coca;
    private javax.swing.JLabel sts_fanta;
    private javax.swing.JLabel sts_ora;
    private javax.swing.JTable tbl_Orders;
    private javax.swing.JLabel timeLab;
    // End of variables declaration//GEN-END:variables

    
}
