/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.AdminPanels;

import Controllers.AdminController;
import Controllers.ClientController;
import Controllers.StockController;
import Models.Admin;
import Models.Client;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP OMEN
 */
public class a_panel extends javax.swing.JPanel {

    /**
     * Creates new form a_panel
     */
    public a_panel() {
        initComponents();
        panel_admin.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_admin = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_admins = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        aemail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apass = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        new_pass = new javax.swing.JTextField();
        new_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        panel_admin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jt_admins.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "email", "password"
            }
        ));
        jt_admins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_adminsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt_admins);

        panel_admin.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 710, 550));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 153, 0));
        jButton6.setText("Add New Admin");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panel_admin.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, -1, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 0, 51));
        jButton7.setText("Remove Admin");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panel_admin.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin Password");
        panel_admin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 436, -1, 20));

        aemail.setEnabled(false);
        aemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aemailActionPerformed(evt);
            }
        });
        panel_admin.add(aemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 170, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Admin Password");
        panel_admin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        panel_admin.add(apass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 170, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 153, 0));
        jButton8.setText("Update Admin");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        panel_admin.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        panel_admin.add(new_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 160, -1));
        panel_admin.add(new_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 160, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Admin Email");
        panel_admin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Admin Email");
        panel_admin.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 1180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jt_adminsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_adminsMouseClicked
        // TODO add your handling code here:

        System.out.println( this.jt_admins.getSelectedRow());
        int i = this.jt_admins.getSelectedRow();
        DefaultTableModel    model =  (DefaultTableModel)this.jt_admins.getModel();
        aemail.setText(model.getValueAt(i, 0).toString());
        apass.setText(model.getValueAt(i, 1).toString());
     
    }//GEN-LAST:event_jt_adminsMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String email,password;
        email=new_email.getText();
        password=new_pass.getText();
       Admin na = new Admin(email,password);
       AdminController ac = new AdminController();
       int res = ac.newAdmin(na);
        if( res> 0){
            JOptionPane.showMessageDialog(null, "New Admin Added");
            this.ShowAdmins();
        }else
            JOptionPane.showMessageDialog(null, "Error!");
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void aemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aemailActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
         AdminController ac= new AdminController();
        //AdminInterface ai = new AdminInterface();
        ac.executeChange(aemail, apass);
        this.ShowAdmins();
        JOptionPane.showMessageDialog(null,"Admin Updated");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         String email,password;
        email=aemail.getText();
      
       
        AdminController ac = new AdminController();
       int res = ac.removeAdmin(aemail);
        if( res> 0){
            JOptionPane.showMessageDialog(null, "Admin Deleted!");
            this.ShowAdmins();
        }else
            JOptionPane.showMessageDialog(null, "Error!");
    }//GEN-LAST:event_jButton7ActionPerformed

    
    
      public void ShowAdmins()
   {
       AdminController ac = new AdminController();
       ArrayList<Admin> alist = ac.getAdminList();
       DefaultTableModel model = (DefaultTableModel)jt_admins.getModel();
       model.setRowCount(0);

       Object[] row = new Object[4];
       for(int i = 0; i < alist.size(); i++)
       {
           row[0] = alist.get(i).getAEmail();
           row[1] = alist.get(i).getAPassword();
        
       
           
           model.addRow(row);
       }
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aemail;
    private javax.swing.JTextField apass;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jt_admins;
    private javax.swing.JTextField new_email;
    private javax.swing.JTextField new_pass;
    private javax.swing.JPanel panel_admin;
    // End of variables declaration//GEN-END:variables
}
