/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.AdminPanels;

import Controllers.ClientController;
import Models.Client;
import Views.AdminInterface;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP OMEN
 */
public class c_panel extends javax.swing.JPanel {

    /**
     * Creates new form c_panel
     */
    public c_panel() {
        initComponents();
                    panel_details.setOpaque(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_details = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        clientsjt = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cemail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cpass = new javax.swing.JTextField();

        panel_details.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clientsjt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "email", "name", "password"
            }
        ));
        clientsjt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientsjtMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(clientsjt);

        panel_details.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 710, 550));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 153, 0));
        jButton6.setText("Update Client");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panel_details.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 0, 51));
        jButton7.setText("Remove Client");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panel_details.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Client Email");
        panel_details.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        cemail.setEnabled(false);
        cemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cemailActionPerformed(evt);
            }
        });
        panel_details.add(cemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 170, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Client Name");
        panel_details.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        panel_details.add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 170, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Client Password");
        panel_details.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));
        panel_details.add(cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_details, javax.swing.GroupLayout.PREFERRED_SIZE, 1180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_details, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clientsjtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientsjtMouseClicked
        // TODO add your handling code here:

        System.out.println( this.clientsjt.getSelectedRow());
        int i = this.clientsjt.getSelectedRow();
        DefaultTableModel    model =  (DefaultTableModel)this.clientsjt.getModel();
        cemail.setText(model.getValueAt(i, 0).toString());
        cname.setText(model.getValueAt(i, 1).toString());
        cpass.setText(model.getValueAt(i, 2).toString());
    }//GEN-LAST:event_clientsjtMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        ClientController cc= new ClientController();
        //AdminInterface ai = new AdminInterface();
        int res =cc.executeChange(cemail, cname, cpass);
        this.ShowClients();
        
        if( res> 0){
            JOptionPane.showMessageDialog(null, "Client Updated!");
            this.ShowClients();}else
                        JOptionPane.showMessageDialog(null, "Error");

    }//GEN-LAST:event_jButton6ActionPerformed

    private void cemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cemailActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
           String email,password;
        email=cemail.getText();
      
       
        ClientController cc = new ClientController();
       int res = cc.removeClient(cemail);
        if( res> 0){
            JOptionPane.showMessageDialog(null, "Client Deleted!");
            this.ShowClients();
        }else
            JOptionPane.showMessageDialog(null, "Error!");
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    
     public void ShowClients()
   {
       ClientController cc = new ClientController();
       ArrayList<Client> clist = cc.getClientList();
       DefaultTableModel model = (DefaultTableModel)clientsjt.getModel();
       model.setRowCount(0);

       Object[] row = new Object[4];
       for(int i = 0; i < clist.size(); i++)
       {
           row[0] = clist.get(i).getEmail();
           row[1] = clist.get(i).getName();
           row[2] = clist.get(i).getPassword();
       
           
           model.addRow(row);
       }
    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cemail;
    public javax.swing.JTable clientsjt;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField cpass;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel_details;
    // End of variables declaration//GEN-END:variables

    
}
