/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.AdminPanels;

import Controllers.AdminController;
import Controllers.StockController;
import Models.Admin;
import Models.Order;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP OMEN
 */
public class o_panel extends javax.swing.JPanel {

    /**
     * Creates new form o_panel
     */
    public o_panel() {
        initComponents();
        panel_orders.setOpaque(false);
    }

    
       public void ShowOrders()
   {
       AdminController ac = new AdminController();
       ArrayList<Order> oList = ac.getOrderList();
       DefaultTableModel model = (DefaultTableModel)jt_orders.getModel();
       model.setRowCount(0);

       Object[] row = new Object[4];
       for(int i = 0; i < oList.size(); i++)
       {
           row[0] = oList.get(i).getCemail();
           row[1] = oList.get(i).getPrice();
           row[2] = oList.get(i).getDate();
           row[3] = oList.get(i).getFulldate();

       
           
           model.addRow(row);
       }
   }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_orders = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_orders = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ordertime = new javax.swing.JTextField();

        panel_orders.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jt_orders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Client Email", "Full Price", "Time", "Date"
            }
        ));
        jt_orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_ordersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt_orders);

        panel_orders.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 400, 300));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 0));
        jButton1.setText("Confirm Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel_orders.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 130, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 0));
        jButton2.setText("Delete Order");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel_orders.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, 140, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Full Orders List");
        panel_orders.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 150, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Order Time");
        panel_orders.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, -1, -1));

        ordertime.setEnabled(false);
        panel_orders.add(ordertime, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_orders, javax.swing.GroupLayout.PREFERRED_SIZE, 1180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_orders, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jt_ordersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_ordersMouseClicked
        // TODO add your handling code here:

        System.out.println( this.jt_orders.getSelectedRow());
        int i = this.jt_orders.getSelectedRow();
        DefaultTableModel    model =  (DefaultTableModel)this.jt_orders.getModel();
        ordertime.setText(model.getValueAt(i, 2).toString());
     
    }//GEN-LAST:event_jt_ordersMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                  String date;
                  date=ordertime.getText();
      
       
        AdminController ac = new AdminController();
       int res = ac.ConfirmOrder(ordertime);
        if( res> 0){
            JOptionPane.showMessageDialog(null, "Order Accepted!");
            this.ShowOrders();
        }else
            JOptionPane.showMessageDialog(null, "Error!");
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            String date;
                  date=ordertime.getText();
      
       
        AdminController ac = new AdminController();
       int res = ac.ConfirmOrder(ordertime);
        if( res> 0){
            JOptionPane.showMessageDialog(null, "Order Deleted!");
            this.ShowOrders();
        }else
            JOptionPane.showMessageDialog(null, "Error!");
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jt_orders;
    private javax.swing.JTextField ordertime;
    private javax.swing.JPanel panel_orders;
    // End of variables declaration//GEN-END:variables
}
